// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SaveFileToPath(arg1, arg2) {
  return window['go']['main']['App']['SaveFileToPath'](arg1, arg2);
}

export function WriteFile(arg1) {
  return window['go']['main']['App']['WriteFile'](arg1);
}
