// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ReadFile():Promise<main.FileData>;

export function SaveFileAs(arg1:string):Promise<main.SaveData>;

export function SaveFileToPath(arg1:string,arg2:string):Promise<string>;

export function WriteFile(arg1:string):Promise<string>;
